# Generated by Django 4.2.6 on 2023-10-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=50)),
                ('taille', models.CharField(max_length=4)),
                ('status', models.CharField(max_length=1)),
                ('ref', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
