# Generated by Django 4.2.6 on 2023-10-28 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu', models.CharField(max_length=50)),
                ('favorite', models.BooleanField(default=False, verbose_name='Favoris')),
            ],
        ),
        migrations.CreateModel(
            name='Preparateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taille', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=15)),
                ('ref', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('finish', models.BooleanField(default=False, verbose_name='Terminée')),
                ('hidden', models.BooleanField(default=False, verbose_name='Cachée')),
                ('adr', models.BooleanField(default=False)),
                ('quai', models.BooleanField(default=False, verbose_name='En quai')),
                ('nb_palettes', models.IntegerField(default=0)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='livraison_api.destination')),
                ('preparateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preparateur', to='livraison_api.preparateur')),
            ],
        ),
    ]
