# Generated by Django 4.2.6 on 2023-10-15 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livraison_api', '0002_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='livraison_api.destination'),
        ),
    ]
