# Generated by Django 4.2.6 on 2023-10-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison_api', '0003_alter_livraison_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livraison',
            name='destination',
        ),
        migrations.AddField(
            model_name='destination',
            name='livraisons',
            field=models.ManyToManyField(to='livraison_api.livraison'),
        ),
    ]
