# Generated by Django 4.2.6 on 2023-10-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison_api', '0003_alter_livraison_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='status',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='taille',
            field=models.CharField(max_length=15),
        ),
    ]
