# Generated by Django 4.2.6 on 2023-10-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison_api', '0005_livraison_finish_alter_destination_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Cachée'),
        ),
    ]
