# Generated by Django 4.2.6 on 2023-10-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison_api', '0007_livraison_adr'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='quai',
            field=models.BooleanField(default=False, verbose_name='En quai'),
        ),
    ]
