# Generated by Django 4.2.6 on 2023-10-25 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livraison_api', '0008_livraison_quai'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preparateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='livraison',
            name='commentaires',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='nb_palettes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='livraison',
            name='preparateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preparateur', to='livraison_api.preparateur'),
        ),
    ]
