# Generated by Django 4.2.6 on 2023-10-28 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livraison_api', '0009_preparateur_livraison_commentaires_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveSmallIntegerField(verbose_name='Numéro')),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='destination',
            name='favorite',
        ),
        migrations.AlterField(
            model_name='livraison',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='livraison_api.destination'),
        ),
        migrations.AddField(
            model_name='destination',
            name='favorite',
            field=models.ManyToManyField(to='livraison_api.semaine'),
        ),
    ]
